# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K5J568PztpKE1k_lIPrKdVC10u4vKJoO
"""

x=10

print(x)

x=10
y=20

print(x+y)

x*y

x-y

x/y

x=10
type(x)

x=10.5
type(x)

x='jamal'

print(x)

type(x)

x='Mohammed'
y='Farzeen'

x+y

x="10"
y="20"

x+y

x=input(x)

type(x)

y=int(x)

type(y)

x=int(input("Enter a number"))

y=int(input("enter a number"))

x+y

x*y

x/y

p=int(input("enter intial principal bal"))
r=int(input("enter annual interest rate"))
t=int(input("enter time"))

A=p*(1+r*t)

print(A)

p*r*t

n=10

c=p*(1+r/n)*n*t

n*t

20**20

c=p*(1+r/n)*20

print(c)

